### ISSUE TITLE
Wrong number of fields

### ISSUE THREAD

**Issue by Alan-Manning** [ptdewey/pendulum-nvim#18]
I keep getting the issue when i try to open the time tracker that there is the wrond number of fields:
```
RPC request failed: Vim:Error invoking 'pendulum' on channel 163:
record on line 22097: wrong number of fields
```

![Image](https://github.com/user-attachments/assets/e60c3cdb-b01e-4b25-9c51-cffb9546bf3d)

This is the line that causes the issue.

If i sort the csv produced then i see the offending entries:

![Image](https://github.com/user-attachments/assets/2d61b3ff-abb2-40f9-9712-cf455a3508d0)

![Image](https://github.com/user-attachments/assets/ee88fce5-bce7-438f-8ed2-bfe5f898d8bd)

I dont know specifically what causes this to be inserted into the csv log but i do often have multiple instances of nvim active in different terminal panes which could be something like perhaps writing to the file at the same time from two places? Not sure.

I think this is a lua issue [here](https://github.com/ptdewey/pendulum-nvim/blob/bdae9ebefdf359acbddc76b59c143f51d581d543/lua/pendulum/csv.lua#L15) There should be some error checking on the number of cols for the data. this would ensure the validity of the csv written [here](https://github.com/ptdewey/pendulum-nvim/blob/bdae9ebefdf359acbddc76b59c143f51d581d543/lua/pendulum/csv.lua#L60).

I dont know enough about lua to do this but i think this is what needs to be done. There may be extra stuff that come with this like concating the time diffs if this fails such that the time tracker still functions but i havent looked into this much more.

Thank you
 - Alan Manning

**Comment by ptdewey** [comment]
Thanks for bringing this up! I've known about this issue for a while at this point, but I haven't gotten around to fixing it yet. Setting up validation on the number of columns is probably a fine approach, so I'll look into doing that when I get a chance.

**Comment by ptdewey** [comment]
I pushed a fix in the latest commit. It won't remove bad rows from the file, but it should prevent new ones from showing up in the future. 

Please let me know if you run into the issue again.

**Comment by Alan-Manning** [comment]
very nice cheers. i have updated and cleaned up the csv. i think i still have some issues with that as some projects show 0 hours even though they had like 18 hours before. I think the active column might be incorrect somewhere due to deleting the rows that were wrongly inserted. Might need to just chalk it up as lost for those projects as it seems to be recording from now as if i just opened them. more digging required if i can be bothered about that :) but fine for now thank you. Ill reopen another issue if this problem comes up again.

Thank you
 - Alan Manning

**Comment by ptdewey** [comment]
Its possible there is some flawed logic in the calculations, I've been unsure about that for a while but haven't had time to extensively test it. I have a hunch there might be some weird stuff going on with time zones as well.
